image: atlassian/default-image:3

pipelines:
  branches:
    sugon-pr/*:
      - step:
          clone:
            depth: full
          script:
            - git push -f https://${GH_TOKEN}@github.com/${GH_USER}/${BITBUCKET_REPO_FULL_NAME##*/} ${BITBUCKET_BRANCH}
