name: Sugon Pull PR from Bitbucket

on:
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "${{ vars.PR_REPO_URL }}"
        source_branch: "*"
        destination_branch: "*"
        sync_tags: "true"
        github_token: ${{ secrets.PAT }}
